name: Application

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

env:
    BUILD_TYPE: Debug

jobs:
    build:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Vcpkg
              uses: lukka/run-vcpkg@v11
              with:
                  vcpkgGitCommitId: bd136dad4da8059ba93f71412f52b2ec7c09d377

            - name: Build
              run: |
                  mkdir build && cd build
                  cmake .. --preset x64-windows -DBUILD_TESTING=True -DBUILD_CLI=True
                  cmake --build .

            - name: Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: build-artifact
                  path: build

    tests:
        runs-on: windows-latest
        needs: [build]
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Artifact
              uses: actions/download-artifact@v4
              with:
                  name: build-artifact
                  path: build

            - name: Tests
              run: |
                  cd build
                  ctest -C Release
                  
