name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Conan
      uses: turtlebrowser/get-conan@main
    
    - name: Build
      run: |
        mkdir build && cd build
        conan install .. -s build_type=${{env.BUILD_TYPE}}
        cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build . --config ${{env.BUILD_TYPE}}
        
    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-artifact
        path: build

  tests:
    runs-on: windows-latest
    needs: [build]
    steps:
    - name: OpenCppCoverage
      run: |
        choco install -y opencppcoverage

    - name: Artifact
      uses: actions/download-artifact@v2
      with:
        name: build-artifact
        path: build
    
    - name: Tests
      run: |
        echo $env:Path
        cd build
        opencppcoverage --quiet --export_type=cobertura:opencppcoverageCoverage.xml --working_dir . -- bin/IzInjectorTests.exe
        type opencppcoverageCoverage.xml
